// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efwwblbskmswttmcqxem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmd3dibGJza21zd3R0bWNxeGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Nzk5ODQsImV4cCI6MjA2NzQ1NTk4NH0.kwU-lzFy1-ztiAKbAkdSQhOfzYj9ZFdNre4OOGsTPCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});